---
title: "Police Complaints"
author: "David Kane"
date: "6/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r get-data}
raw_data <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv", 
              col_types = cols(complaint_id = col_character(),
                               date_received = col_date(format = ""),
                               district_occurrence = col_character(),
                               general_cap_classification = col_character(),
                               summary = col_character(),
                               officer_id = col_factor(),
                               po_race = col_character(),
                               po_sex = col_character(),
                               po_assigned_unit = col_character(),
                               allegations_investigated = col_character(),
                               investigative_findings = col_character(),
                               disciplinary_findings = col_character())) %>% 
  select(officer_id, po_race, po_sex)
```


```{r, clean_data}
clean_data <- raw_data %>% 
  group_by(officer_id) %>% 
  summarise(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_percentage = compl_total/sum(compl_total))
```


```{r, plot_data}
clean_data %>% 
  slice(1:10) %>% 
  ggplot(aes(x = fct_reorder(officer_id, total), y = total)) +
    geom_col() +
    coord_flip() +
    labs(title = "Complaints about Police Officers in Philadelphia",
         subtitle = "Most complained about officers have many more complaints than\nthe typical officer",
         x = "Officer",
         y = "Complaints",
         caption = "Data from Financial Times") 
  
```

Could also keep around race and then use fill/color to color the bars by race. Then add
